rebaseMergeAllowed: true
squashMergeAllowed: true
mergeCommitAllowed: false
branchProtectionRules:
  - pattern: main
    isAdminEnforced: false
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: true
    requiredStatusCheckContexts:
      - cla/google
      - docs
      - lint
      - test (18)
      - windows
  - pattern: 12.x
    isAdminEnforced: false
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: true
    requiredStatusCheckContexts:
      - cla/google
      - docs
      - lint
      - test (12)
      - test (14)
      - test (15)
      - windows
permissionRules:
  - team: yoshi-admins
    permission: admin
  - team: yoshi-nodejs-admins
    permission: admin
  - team: yoshi-nodejs
    permission: push
